language: cpp

jobs:
  include:
  - name: Ubuntu 18.04 LTS - Bionic
    dist: bionic
    addons:
      apt:
        sources:
        # Official Kitware APT repository. Currently supports Bionic and Xenial.
        # More information at: https://apt.kitware.com
        - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
          key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
        # Optional to get release candidates when available.
        - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic-rc main'
        packages:
        - cmake
    install: whereis apt

  - name: Ubuntu 16.04 LTS - Xenial
    dist: xenial
    addons:
      apt:
        sources:
        - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
          key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
        - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial-rc main'
        packages:
        - cmake

  - name: Ubuntu 14.04 LTS - Trusty
    dist: trusty
    addons:
      apt:
        packages:
        - cmake

  - name: Ubuntu 12.04 LTS - Precise
    dist: precise
    addons:
      apt:
        packages:
        - cmake

  allow_failures:
  - dist: bionic # APT script is not working on Bionic

before_script:
- |
  function cond_call {
    if [[ "$(command -v $1)" ]]; then
      echo "Command: $1"
      echo "Verbose: $(command -v $1)"
      $@ --version
      echo "----------------"
    fi
  }

script:
- lsb_release --all
- apt-cache show cmake -a | grep Version
- cond_call cmake
- |
  LOCATIONS="$(whereis cmake)"
  for LOCATION in ${LOCATIONS:-}; do
    cond_call $LOCATION
  done
- cond_call /usr/local/cmake/bin/cmake # secondary location on Xenial
- hash
- echo $PATH
