language: cpp
os: osx

jobs:
  include:
  - osx_image: xcode11
  - osx_image: xcode10.2
  - osx_image: xcode10.1
  - osx_image: xcode10
  - osx_image: xcode9.4
  - osx_image: xcode9.3
  - osx_image: xcode9.2
  - osx_image: xcode9.1
  - osx_image: xcode9
  - osx_image: xcode8.3
  - osx_image: xcode8
  - osx_image: xcode7.3
  - osx_image: xcode6.4

before_script:
- |
  function cond_call {
    if [[ "$(command -v $1)" ]]; then
      echo "Command: $1"
      echo "Verbose: $(command -v $1)"
      $@ --version
      echo "---------------------------"
    fi
  }

script:
- |
  cond_call "g++"
  cond_call "g++-9"
  cond_call "g++-8"
  cond_call "g++-7"
  cond_call "g++-6"
  cond_call "g++-5"
  cond_call "g++-4.9"
- brew list
